name: Build

on:
  push:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build
      run: ./gradlew --no-daemon iris
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: iris.jar
        path: build/libs/Iris-*.jar
        if-no-files-found: error
        retention-days: 90
